server:
  port: 3232   #端口配置
  context-path: /nyhx   #配置项目路径
debug: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nyhx
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    #驱动
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
       #自动更新
      ddl-auto: update
      naming:
        #表名配置大写
        physical-strategy: com.iron.config.UpperTableStrategy
    #日志中显示sql语句
    show-sql: true